### ISSUE TITLE
The "user" option does not exist

### ISSUE THREAD

**Issue by shasta123** [nextcloud/sharelisting#310]
Hi,

I just noticed (after upgrading to NC 24) that occ sharing:list constantly outputs

The "user" option does not exist.

no matter what options (if any) I  specify.

On first glance I spot nothing in the log file.

Cheers,
Michael

**Comment by support-tt** [comment]
Same Problem here Nextcloud:
```
php occ status
  - installed: true
  - version: 24.0.0.12
  - versionstring: 24.0.0
  - edition: 
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false
```
```
php occ sharing:list --user admin                        
The "user" option does not exist.  
sharing:list [-u|--user [USER]] [-p|--path [PATH]] [-t|--token [TOKEN]] [-f|--filter [FILTER]]
```
```
php occ sharing:list -u admin
The "user" option does not exist.  
sharing:list [-u|--user [USER]] [-p|--path [PATH]] [-t|--token [TOKEN]] [-f|--filter [FILTER]]

```
